Sprint 4
kamad1/MovieQuiz-ios pull request #1
Opened 2023-05-11 20:05 UTC by kamad1

Создал ветку выполнил задание. Хотел прописать weak для self в замыкании но почему то выдавало ошибку постоянно зато в аутлеты добавил без проблем. Так же до работал рамку установил цвет 0 при смене вопроса.

2023-05-12 09:27 UTC, mmbabaev requested changes

2023-05-12 09:27 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction private func noButtonClicked(_ sender: Any) {
порядок в viewController обычно делают такой: 

1. Properties
2. override funcs
3. IBAction funcs
4. other funcs  другие типы - сверху или снизу

2023-05-12 09:27 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let questionStep = QuizStepViewModel( // 1
лучше не копировать код из учебника, а набирать руками. Или хотя бы почистить комментарии //1

2023-05-12 09:27 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.masksToBounds = true
здесь нужно добавить округление кнопки

2023-05-12 09:27 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.masksToBounds = true
свойство - imageView.layer.cornerRadius

2023-05-13 19:30 UTC, merged

2023-05-13 19:31 UTC, kamad1 commented
Спринт №5